import { Project } from "@/types";

export const recentProjects: Project[] = [
  {
    id: "shinhan",
    title: "shinhan.title",
    description: "shinhan.description",
    technologies: ["Vue.js", "Java", "Spring-boot", "Maven"],
    githubLink: "",
    demoLink: "https://efx.shinhan.com/",
    image: "/projects/shinhan.png",
    role: "shinhan.role",
    tasks: "shinhan.tasks",
    period: "[2025.06 - 2026.02]",
  },
  {
    id: "yujin",
    title: "yujin.title",
    description: "yujin.description",
    technologies: ["SCSS", "JavaScript", "Java", "Spring-boot", "Gradle"],
    githubLink: "",
    demoLink: "https://www.eugenefutures.com/OptionsHub/index.html",
    image: "/projects/yujin.png",
    role: "yujin.role",
    tasks: "yujin.tasks",
    period: "[2025.03 - 2025.06.15]",
  },
  {
    id: "vue",
    title: "vue.title",
    description: "vue.description",
    technologies: ["Vue.js", "Pinia", "JSON Server", "Tailwind CSS"],
    githubLink: "https://github.com/bekov28/jobs-website-vue",
    demoLink: "https://jobs-website-vue.netlify.app/",
    image: "/projects/vue.png",
    role: "vue.role",
    tasks: "vue.tasks",
    period: "[2025.06]",
  },
];
