import { Project } from "@/types";

export const sideProjects: Project[] = [
  {
    id: "vueJobs",
    title: "vueJobs.title",
    description: `vueJobs.description`,
    technologies: ["Vue.js", "Pinia", "JSON Server", "Tailwind CSS"],
    githubLink: "https://github.com/bekov28/jobs-website-vue",
    demoLink: "https://jobs-website-vue.netlify.app/",
    image: "/projects/vue.png",
    role: "",
    tasks: "",
    period: "",
  },
  {
    id: "graniteShop",
    title: "graniteShop.title",
    description: `graniteShop.description`,
    technologies: ["Vue.js", "Pinia", "Firebase", "Bootstrap"],
    githubLink: "https://github.com/bekov28/granite-online-shop",
    demoLink: "https://graniteshop-29e1a.web.app/",
    image: "/projects/stone-website.png",
    role: "",
    tasks: "",
    period: "",
  },
  {
    id: "camper",
    title: "camper.title",
    description: `camper.description`,
    technologies: ["React.js", "MUI", "Styled components", "React Router", "EmailJS"],
    githubLink: "https://github.com/bekov28/camper-project-react",
    demoLink: "https://campertestsite.netlify.app/",
    image: "/projects/camper.png",
    role: "",
    tasks: "",
    period: "",
  },
];
