name: Lighthouse Audit
on:
  push:
    branches: [main]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  generate_badges:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Generate Lighthouse Badges
        uses: myactionway/lighthouse-badger-action@v2.2
        with:
          urls: "https://misterberd.com" # Replace with your URL
          label: "Lighthouse"
          # This stores badges in a branch called 'badges'
          repo_token: ${{ secrets.GITHUB_TOKEN }}
